
import { Inter } from "next/font/google";
import Sidebar from "../components/sidebar";
import Header from "../components/header"; 
import "../styles/globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Winsoft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className="layout">
          <Sidebar/>
          
          
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
